apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: worker
spec:
  selector:
    matchLabels:
      app: worker
  replicas: 1
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: master
        image: prajaktakini17/lab7-worker:v15
        resources:
          requests:
            cpu: 100m
            memory: 400Mi
        ports:
        - containerPort: 6379
        env:
          - name: REDIS_HOST
            value: "redis"
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_QUEUE
            value: "toWorkers"
          - name: "MINIO_ENDPOINT"
            value: "minio.minio-dev.svc.cluster.local:9000"
          - name: "MINIO_ACCESS_KEY"
            value: "minioadmin"
          - name: "MINIO_SECRET_KEY"
            value: "minioadmin"
          - name: "LOGGING_WORKER_QUEUE"
            value: "logging"